### ISSUE TITLE
Prevent user scaling, fix at 100%

### ISSUE THREAD

**Issue by milesgreen** [GoogleWebComponents/model-viewer#696] opened 2019-08-07 15:41 UTC
Feature Request:

Ability to configure preventing user from scaling the 3D object. Fix at 100%.

In some instances, it would be useful to prevent the user from (intentionally or inadvertently) scaling the object - particularly when doing product previews, where object scale might be important.

**Comment by cdata** [comment] 2019-08-07 17:20
Thanks for the request! I'm going to mark this as a dupe of #458 because that bug covers customizing the minimum / maximum radius that the camera can be from the model. You could "fix the scale by saying that the min and max radius are the same.

**Closed** 2019-08-07 17:20 UTC
Labels: flag: duplicate, type: feature
