### ISSUE TITLE
IE11 gl.getExtension CI failure

### ISSUE THREAD

**Issue by jsantell** [GoogleWebComponents/model-viewer#252] opened 2018-12-03 19:40 UTC
https://travis-ci.org/GoogleWebComponents/model-viewer/builds/461972545

**Comment by cdata** [comment] 2018-12-03 22:20
Gonna mark this as a dupe of #253 cause I already put the other one in the project board. Sorry about the overlap!

**Closed by cdata** 2018-12-03 22:20 UTC
Labels: flag: duplicate, type: bug
