### ISSUE TITLE
Tilt effect on scroll

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#600] opened 2019-06-04 16:31 UTC
Another subtle effect for showing that what is in the viewer is realtime 3D is to have the model tilt slightly on scroll.  See demo here: https://panic.com/transmit/

![tilt](https://user-images.githubusercontent.com/190692/58896455-06f5e100-86c4-11e9-9592-0646c22417af.gif)

One consideration is not too tilt it too much because the underside of models are not always the things you want to focus on. For example for products like a table, seeing the bottom of the table might not be where you want to draw user's eyes too since it might be a weird angle to show the product in.

In the truck example above it's nice that the truck already starts with the camera looking down on it, so you never get to a point where you're staring at the bottom of the truck.

Complimentary feature to: #595

**Comment by pushmatrix** [comment] 2019-06-05 00:56
It would be great to have the axis be configurable too, so when you scroll it would rotate left and right instead of tilting up and down. Nice and eye catching!

![rotate](https://user-images.githubusercontent.com/190692/58922920-2a904a00-870b-11e9-8429-07623ea0c571.gif)


Try it here: https://vanilla-hawk.glitch.me/

**Comment by pushmatrix** [comment] 2019-08-30 20:41
Yeah what I like about that is that we don't depend on yet another attribute. Seems more flexible this way.

**Comment by cdata** [comment] 2019-09-03 15:49
I have been experimenting with the approach I described, and I'm feeling tentatively positive about the results:

![calc](https://user-images.githubusercontent.com/240083/64188229-da6a7600-ce26-11e9-8917-5967a0b88e46.gif)

The configuration for the above demo looks like this:

```html
<model-viewer camera-orbit="calc(-1.5rad + env(window-scroll-y) * 4rad)
                            calc(0deg + env(window-scroll-y) * 180deg)
                            calc(3m - env(window-scroll-y) * 1.5m)"
              src="assets/Astronaut.glb"
              background-color="#622dcf"
              alt="A 3D model of an astronaut">
</model-viewer>
```

This is a worst-case scenario for verbosity, as I have configured a `calc()` expression for every term of the `camera-orbit`. You can, of course, mix and match the configuration to suite your needs just like you would in CSS.

**Comment by pushmatrix** [comment] 2019-09-03 16:19
That looks awesome! And if you tumble the model with camera-controls, does it screw it up?

**Comment by cdata** [comment] 2019-09-03 16:34
You _can_ configure `camera-controls` to be on. If you do, the user can tumble the model. However, the configured `camera-orbit` value will take precedence and be re-evaluated as soon as the next scroll happens.

Here is an example of what this looks like in practice:

![calc2](https://user-images.githubusercontent.com/240083/64191622-b8282680-ce2d-11e9-91a3-e1a6fbacd484.gif)

If you wanted to prevent the camera from re-aligning at the next scroll, you would have to change `camera-orbit` to _not_ contain any reference to `env(window-scroll-y)` (you could do this on first user interaction).

What I landed on here is subjectively good, and doesn't have an obvious correlate in CSS. Please share ideas if you think there is a better outcome!

**Comment by pushmatrix** [comment] 2019-09-03 16:36
Yeah that makes sense. I like it!

**Comment by valdrinkoshi** [comment] 2019-09-10 14:15
This is very cool! Do you think it would be easy to support coordination between iframes in order to pass the scroll position? The scenario I'm thinking of is when the HTML page that displays the 3d model must be hosted in a different domain, and the main HTML page in the top window can afford to coordinate with the 3d model iframe to pass data through postMessage() APIs.
Would it be enough to use a custom CSS property in the 3d model page for this scenario? e.g.

```html
<model-viewer camera-orbit="calc(-1.5rad + var(--top-window-scroll-y, 0) * 4rad)
                            calc(0deg + var(--top-window-scroll-y, 0) * 180deg)
                            calc(3m - var(--top-window-scroll-y, 0) * 1.5m)"
              src="assets/Astronaut.glb"
              background-color="#622dcf"
              alt="A 3D model of an astronaut">
</model-viewer>
```

**Comment by cdata** [comment] 2019-09-10 23:18
@valdrinkoshi I think we can support a use case like that, but I would like to suggest that it might best be served if we implement the `var()` function. To adapt my original psuedocode, the configuration might look something like this:

```html
<model-viewer src="Astronaut.glb"
  camera-orbit="calc(15deg - var(--your-custom-property) * 30deg) 75deg auto">
</model-viewer>
```

In this example, `var(--your-custom-property)` would be placed with the computed CSS property value of `--your-custom-property` on the `<model-viewer>` instance.

For the `<iframe>` use case, this means you would have to coordinate between parent and child frame to determine the scroll position, and then set that position as a CSS custom property that styles the `<model-viewer>` element.

WDYT?

**Comment by valdrinkoshi** [comment] 2019-09-11 03:43
Yes that works! I'm not sure the performance implications of computing the `--your-custom-property` value, but in terms of DevX this would be perfect 👌

**Comment by cdata** [comment] 2019-09-11 14:53
Yeah, we will need to investigate the performance consequences when implementing this. It will involve invoking `window.getComputedStyle(modelViewer)` on a rAF, which seems bad but might not be (all children are in a shadow root with [`contain: strict`](https://github.com/GoogleWebComponents/model-viewer/blob/master/src/template.ts#L26) set for the host).

The main concern I have is the potential for severe performance regression on browsers that do not have native Shadow DOM. I think right now that only means IE11, though 🤷‍♂

**Comment by valdrinkoshi** [comment] 2019-09-11 16:52
For the `<iframe>` use case, we'll have to update the inline styles either on `document.documentElement` or the `<model-viewer>` instance itself. Given this, we can avoid invoking `window.getComputedStyle(modelViewer)` and rather check for the inline styles, first on modelViewer, then on the `<html>` element, and keep getComputeStyle as last resource.
As for the rAF timing, we would probably want to compute the value right before we trigger the webgl rendering. Some sort of `onBeforeRender` mechanism/callback/event might be needed in the Renderer.

**Comment by cdata** [comment] 2019-09-11 19:54
Internally, `<model-viewer>` needs to `window.getComputedStyle` on itself in order to measure the style value.

**Closed** 2019-10-15 16:34 UTC
Labels: arc: customization, arc: interaction, flag: partner, type: feature

**Comment by SimonKefas** [comment] 2022-02-08 10:36
@cdata Hi! Do you have any idea how i could be able to [cycle models](https://modelviewer.dev/examples/loading/#cyclingModels) on specific scroll % of page?

**Comment by elalish** [comment] 2022-02-08 23:09
You can do it with JS, but there isn't a declarative API. If you have trouble, start a discussion with the code you have so far and  a live link.

**Comment by trusktr** [comment] 2024-01-25 23:27
CSS has [`perspective-origin`](https://developer.mozilla.org/en-US/docs/Web/CSS/perspective-origin) for this. To help align future 3D elements with current standards, it would be nice implement this in a way that makes the model-viewer's content align with CSS 3D space and its coordinate system.

I've started working on this over at [Lume](https://lume.io/), where the coordinate system is based on `DOMMatrix` (Y down, rotations are left-handed, elements have a size, and top/left/back is 0,0,0 in CSS `px` units such that when an element of size `10,10,10` has a position of 0,0,0, it will be 10x10x10 in CSS px, and this will align with CSS `perspective` such that if the CSS perspective is `800`, then an element as Z position `800` will be at the camera, etc).

I'd like to throw in my own `<model>` and `<model-viewer>` alternative to help to ideate what it could look like to be aligned with CSS (including styling the 3D features such as `perspective-origin`, etc, with CSS).

**Comment by trusktr** [comment] 2024-01-25 23:53
Here's a CSS 3D example (CSS for styling including `perspective` and `perspective-origin`, and JS to animate the `perspective-origin` based on scroll position so that, no matter the scroll position, the perspective origin remains center view):

https://codepen.io/trusktr/pen/wvOPBJg
