### ISSUE TITLE
Object is black on some Android devices

### ISSUE THREAD

**Issue by AytoMaximo** [GoogleWebComponents/model-viewer#679] opened 2019-07-20 09:11 UTC
### Description

The relevant THREE github issue on this case: https://github.com/mrdoob/three.js/issues/14137. It was opened more than year ago and there is still no solution. Model-view player based on the same THREE.js library, but it does not work on a lot of popular devices. For example, many Xiaomi phones (even flagman ones) can't work with it. Tested on Redmi 4A (Adreno 308), Mi A1 (Adreno 506), Mi6 (Adreno 540). More devices with black textures issue can be found by the link above. 

Errors in the console: 
- WEBGL_depth-texture extension not supported
- OES_texture_float_linear extension not supported
- EXT_shader_texture_lod extension not supported.

Screenshot of our own [test](https://image.faradise.ru/arcore.html) , but can also be produced on the main page with astronaut. 
![ShooterScreenshot-22-18-07-19](https://user-images.githubusercontent.com/14392087/61576715-fc61a080-aae5-11e9-9ca1-e9917bd2c5a1.png)

### Browser Affected

- [x] Chrome
- [x] Firefox

I guess all available for Android platform browsers are affected. 

### OS

- [x] Android

### Additional information
1. The problem is in MeshStandartMaterial (https://threejs.org/docs/#api/en/materials/MeshStandardMaterial). We use difuse, normal, metallic and roughness maps with this shader and get black texture problem in our own project with THREE.js too. I think the astronaut in model-viewer inherits the same issue. 
2. From the documenation about MeshStandartMaterial we can get that it's about "physically based rendering (PBR) has recently become the standard in many 3D applications, such as Unity, Unreal and 3D Studio Max.". Ok, I'm Unity developer, so let's do the test. 
  - Open Unity 2019.1
  - Create project with LightWeightPipeline
  - Choose shader for material object similiar to THREE's MeshStandartMaterial. I'll attach the screenshots from Unity and THREE editor. Shaders parametres are very similiar. 
  - Make a build
  - That's it, rendering is fine! 

![Unity-PBR-LWP](https://user-images.githubusercontent.com/14392087/61576765-91fd3000-aae6-11e9-8727-5557e99049b9.png)
![THREE-Editor-PBR](https://user-images.githubusercontent.com/14392087/61576769-945f8a00-aae6-11e9-9142-79753c2e1f53.png)

So, I supppose the phones are OK with PBR and can handle diffuse/normal/metallic/rougness shader. THREE's developers think that there is nothing they can do. 

I hope google engineers can handle this issue together with THREE developers, because Web AR really depends on it.

**Comment by cdata** [comment] 2019-07-30 21:42
@AytoMaximo thanks for reporting. I only glanced at the upstream Three.js issue, but it sounds like they decided that this is a WebGL / vendor-specific issue?

Are you seeing this problem on all devices, or on a specific Android device?

**Comment by AytoMaximo** [comment] 2019-07-31 05:58
@cdata I've tested on Xiaomi devices, all of them have this issue. 
- Redmi 4A (Adreno 308)
- Mi A1 (Adreno 506)
- Mi6 (Adreno 540).

Also, you can get a big list of devices from the https://github.com/mrdoob/three.js/issues/14137 thread:

- LG Aristo (LG-M210) (by me)
- LG Fiesta (LG L63BL) (by me)
- Motorolla Moto G3
- Samsung Galaxy J3 Mission (SM-J327VPP)
- Huaweï MediaPad T3 10 (AGS-L09) - Androïd 7 / EMUI 5.1 / Snapdragon 425 / 2Go RAM / 800x1280
- Samsung SM-T555 (Galaxy A)
- Acer Predator 8 (GT-810 rolex), Android 7.1
- LG K20 Plus (lv517), Android 7.0
- Galaxy Tab A 9.7 (gt510wifi), Android 7.1
- Moto G4 Play (harpia), Android 7.1
- Galaxy Tab E 9.6 (gtelwifiue), Android 7.1
- Galaxy J5(2016) (j5xnlte), Android 7.1
- Galaxy Tab A 9.7 (gt510wifi), Android 7.1
- HM NOTE 1LTETD (dior), Android 4.4](#12679 (comment))

They can't decide that it is a WebGL issue 'cas from the first post we see the following:
"This doesn't appear to be a problem with all WebGL texturing, though -- https://fltr.world/ (simple texture demo implemented with three.js shaders) works fine, as does https://webglsamples.org/aquarium/aquarium.html"(c). 

The first link is unreachable, however the aquarium is really fine. 

Also, that's why it is not vendor-specific issue, because aquarium is fine, and my example with Unity is fine. 

I also posted the same issue on Chromium bug tracker, they asked me produce a minimal test case that shows that there is a problem with handling of a valid shader on this phone. And suggested these links: https://github.com/KhronosGroup/WebGL , in particular the tests under https://github.com/KhronosGroup/WebGL/tree/master/sdk/tests/conformance/glsl/misc , can be used as a template.

But I'm not shader developer and don't understand what is going on there :( 

It seems like guys really need some help, because they struggle this issue for a year or longer with no results. Moreover, I think the list of devices is very big and it's not over yet, so developing Google AR view with THREE.js library inherits a serious bug.

**Comment by paluh** [comment] 2019-08-20 18:08
I was able to fix rendering on my "Moto G4" by passing `precision: 'lowp'` here: https://github.com/GoogleWebComponents/model-viewer/blob/6eb788f5417ca34155c282199cb92f63cae3507a/src/three-components/Renderer.ts#L75 

This is suggested as an workaround in this thread:

https://github.com/mrdoob/three.js/issues/14137

Of course hardcoding this value doesn't seem like a good solution to the problem.

**Comment by paluh** [comment] 2019-08-20 18:24
I'm not sure if my previous post adds any value to the discussion as @AytoMaximo is aware of this workaround as an active participant of the pointed (in my comment) threejs issue thread. @AytoMaximo should I delete the above workaround suggestion?

**Comment by AytoMaximo** [comment] 2019-09-03 13:52
Sorry for the late answer, had plenty of work to do :)
Unfortunately, now it's black everywhere. On my Windows PC (Chrome) and iOS device too. The same test link: https://image.faradise.ru/arcore.html
Did we mess up something after the update? We turned on automatic updates for this mini-project.
![image](https://user-images.githubusercontent.com/14392087/64179088-3820b180-ce6b-11e9-8e46-30dfeb87de17.png)

**Comment by cdata** [comment] 2019-09-03 15:39
@AytoMaximo We have a similar report in #736 

@elalish I'm tentatively creating a v0.6.1 milestone in case we discover a rendering regression

**Comment by AytoMaximo** [comment] 2019-09-03 16:32
@cdata I've noticed a very funny thing: my Xiaomi Redmi 4A is not showing model in the scene anymore (before it was just black). The situation is the same in our [test project](https://image.faradise.ru/arcore.html) and in model-viewer.glitch.me

![image](https://user-images.githubusercontent.com/14392087/64191580-7628d000-ce81-11e9-92f9-b27c824d9003.png)

**Comment by elalish** [comment] 2019-09-04 16:12
@AytoMaximo Thanks for the info! I've looked at your model and I think I know why it's black: It has an entirely black AO (ambient occlusion) map: 
![image](https://user-images.githubusercontent.com/1649964/64272087-7661b380-cef3-11e9-8f0b-0d7903f8cdf8.png)
I also noticed something strange with the shadow when I turned that on:
![image](https://user-images.githubusercontent.com/1649964/64272049-634ee380-cef3-11e9-915e-a9712f83a9ec.png)
This leads me to believe something else is not quite right with this model - maybe triangle orientation? How was this model created? 

One final question, @donmccurdy this model renders fine in your viewer, which makes me think one or the other of us has a bug. Are we somehow being more strict with our glTF parsing?

**Comment by donmccurdy** [comment] 2019-09-04 16:21
Is there a link to the model? 

My viewer applies some direct light, which isn't affected by AO. If model-viewer is only using indirect lights, that (combined with a black AO map) may be why it's dark.

**Comment by elalish** [comment] 2019-09-04 16:25
Ah yes, that explains it! I used the test model link three posts up; you can pull the model out of that.

**Comment by elalish** [comment] 2019-09-04 16:57
@AytoMaximo Until I manage to get a local repro of your vanished model case, would you be so kind as to expand that shader error and copy the results here for me? That should give me a clear idea of what's going wrong.

**Comment by AytoMaximo** [comment] 2019-09-04 16:57
> @AytoMaximo Thanks for the info! I've looked at your model and I think I know why it's black: It has an entirely black AO (ambient occlusion) map:

As I know, we are using specific texture maps only for android, but our standard map set (for WebGL and iOS) is: diffuse, normal, metallic and roughness. I first faced black texture problem while developing our own THREE.js player. So, I'm sure I was using the map set mentioned above. 

Here the config for our test case: 
`<model-viewer ar src="https://237529.selcdn.ru//awespace/product/6190/8786.glb" alt="3d model Faradise" auto-rotate camera-controls background-color="#ffffff" ios-src="https://237529.selcdn.ru/faradise/product/6190/8786.usdz" ></model-viewer>`

As you can see, there is .USDZ file included for iOS, where the model is also black. Also, iOS .USDZ has metallic+roughnesss maps, not AO. That's for sure. 

I'll check the information about .glb contents with the guy who developed our model converter. Personally, I was very surprised to know about the usage of AO map. I was sure, there is a united metallic/roughness map for android apps.

**Comment by elalish** [comment] 2019-09-04 17:07
> Also, the models for Android include united metallic/roughness map and the black AO map in the Red channel.

I think this is the problem. Why a black AO map? That means all environmental lighting is turned off (which is all we use now, for consistency of rendering).

**Comment by AytoMaximo** [comment] 2019-09-04 17:09
> @AytoMaximo Until I manage to get a local repro of your vanished model case, would you be so kind as to expand that shader error and copy the results here for me? That should give me a clear idea of what's going wrong.

Yes, sure :)
![image](https://user-images.githubusercontent.com/14392087/64276156-e736b900-cf4f-11e9-98d9-5ee9322d2386.png)

**Comment by AytoMaximo** [comment] 2019-09-04 17:13
> I think this is one of the problems. Why a black AO map? That means all environmental lighting is turned off (which is all we use now, for consistency of rendering).

I'm not android developer, so I can't properly answer this question, but  it was the only to make it work on android devices just like other platforms. We couldn't get the proper result in Android studio without this fix. Also, as I know, our android developer was also discussing this issue with Google.

**Comment by elalish** [comment] 2019-09-04 17:19
We have no code to render a USDZ; all we do is pass it to QuickLook on iOS (hence the short transition into AR). If you're not in AR, then on iOS you're still looking at a glTF. If the AR one is black, then QuickLook doesn't like the file either.

I did just notice that you have a warning about not supporting texture_float_linear, which I thought we did not require. I'm going to look into that.

**Comment by AytoMaximo** [comment] 2019-09-04 17:28
> If you're not in AR, then on iOS you're still looking at a glTF

Oh, i see. In AR the model is fine indeed. So, seems like we need to upgrade our glb model for the model-viewer. 

> I did just notice that you have a warning about not supporting texture_float_linear, which I thought we did not require.

This is one of the three errors (there is a list in my first post) inherited from the THREE.js library

**Comment by elalish** [comment] 2019-09-04 17:49
Okay, I've verified that all three of those WebGL extension warnings are okay; three.js looks for each of them, regardless of whether they will be used. We intentionally use none of these so that rendering works without their presence. If you decide to include an AO map without data, ensure it is white, since it is multiplicative (1 has no effect). 

Regarding your shader error, normally it outputs the the line on which the shader compiler had a problem. I'm not sure why it's not doing that here. I may need to get a local repro to debug. Does that only happen on the Xiaomi Redmi 4A?

**Comment by AytoMaximo** [comment] 2019-09-04 18:04
> Does that only happen on the Xiaomi Redmi 4A?

It's the only android device I have access to :( 
I'll ask around, but it's gonna take some time

**Comment by AytoMaximo** [comment] 2019-09-04 18:29
Xiaomi Redmi Note 7 Pro (Snapdragon 660) - OK
Honor 20 (Kirin 980) - OK
Mi A1 (Adreno 506) - OK
Mi6 (Adreno 540) - OK
Redmi 3S (Adreno 505) - OK

Xiaomi Redmi 4A (Adreno 308) - FAIL
Sony Xperia Z (Qualcomm APQ8064) - FAIL

It looks like old devices have some problems. Maybe we need some other reports about Adreno 3xx or 4xx. Just to be sure when the problem starts.

**Comment by elalish** [comment] 2019-09-04 19:29
Great, so it seems the 0.6.0 update did fix at least the 506 and 540 models. If you can change the AO map to white and check that fixes the rendering, that would be helpful. If the only issue left is on old phones and can be fixed by switching to mediump (as stated above, is that still true?), then I would consider making that change here as long as we don't see major moire patterns from it.

**Comment by AytoMaximo** [comment] 2019-09-04 20:42
> If you can change the AO map to white and check that fixes the rendering, that would be helpful. 

So, we changed AO to white and the chair become colorful. However, it's too bright :) 
![image](https://user-images.githubusercontent.com/14392087/64289783-828a5700-cf6d-11e9-885e-8e3ed80e418a.png)

I feel strange about the THREE.js material you are  using. 

I've imported .glb model to THREE.js editor. It's also black, but! because of no directional light was added to the scene. If I add a light, everything will be fine. Changing AO color or disabling it do nothing.

![image](https://user-images.githubusercontent.com/14392087/64287504-91bad600-cf68-11e9-98b9-6cd51836363a.png)
![image](https://user-images.githubusercontent.com/14392087/64287550-aa2af080-cf68-11e9-9c8d-596a3b7d22ed.png)
![image](https://user-images.githubusercontent.com/14392087/64287595-c7f85580-cf68-11e9-9f5b-e01e71af8d8f.png)
![image](https://user-images.githubusercontent.com/14392087/64287647-e9594180-cf68-11e9-9ea9-73a5510a86c1.png)

Also, if I add black AO map to your astronaut, it'll be OK too:
![image](https://user-images.githubusercontent.com/14392087/64288186-21ad4f80-cf6a-11e9-9e81-f91d20218e55.png)

So, the question is: what kind of THREE.js material are you using in model-viewer? For example, MeshBasicMaterial does not need light to be visible (and it's OK if you use only diffuse map). But if you have a set of diffuse, normal, metallic and roughness, you need a MeshStandardMaterial, and this guy need lights in the scene. 

![image](https://user-images.githubusercontent.com/14392087/64289142-57533800-cf6c-11e9-8d6d-9b7cbc5922da.png)

So, that's why we didn't expect the AO map affects anything.

**Comment by elalish** [comment] 2019-09-04 21:03
Thanks for the detailed analysis! Three.js does not apply AO to direct lighting, since this is a more basic lighting type. It is (and always has been) applied to environmental lighting, but you may not have noticed the difference since the render was dominated by the point lights. We recently removed the directional light from <model-viewer>, so all light is now environmental, which gives us a more consistent render because the two lighting types use different approximations. In fact the directional light was hiding a number of our own errors in environmental lighting which have since been corrected. In this case it was also hiding an AO error in the model.

**Comment by elalish** [comment] 2019-09-04 21:05
As for brightness, please take a look at our exposure attribute, which provides the easiest way to adjust this.

**Comment by AytoMaximo** [comment] 2019-09-04 21:14
So, I guess we need to find proper shade of gray color for AO map to make the model look not too bright :) 

Seems like old devices the only painful thing that remains...

**Comment by donmccurdy** [comment] 2019-09-04 21:23
Yeah I wouldn't recommend using AO as a method of controlling overall brightness – if it's going to be a uniform color, you may as well omit AO entirely or use solid white. Anything else is taking you off a physically-plausible rendering path — nothing ever really gets zero indirect light — and lighting adjustments from there on out will likely be hacks.

Environmental lighting is higher quality than punctual/analytical lighting like directional lights. Changing the IBL or changing exposure should be enough to get realistic results. One could debate whether AO should affect IBL, but that's a thorny question and not the source of the problem here. :)

**Comment by AytoMaximo** [comment] 2019-09-05 04:55
What about the problem with shadows? Is it on our side too? 
![image](https://user-images.githubusercontent.com/14392087/64312879-7674b880-cfb2-11e9-8b3b-26d9f56a1934.png)

**Comment by elalish** [comment] 2019-09-05 16:44
Thanks, that's very helpful! I was just cleaning up the shadow code, so I'll be sure to check that it works properly even at 100x scale in 0.7.

**Comment by AytoMaximo** [comment] 2019-09-05 17:41
> Thanks, that's very helpful! I was just cleaning up the shadow code, so I'll be sure to check that it works properly even at 100x scale in 0.7.

Sounds great! We have some problems with the scale while converting models to GLB. So, if model-viewer can handle such cases, it will be very helpful))

**Comment by elalish** [comment] 2019-09-05 18:39
I plan to, but keep in mind, you definitely need proper scale for AR.

**Comment by AytoMaximo** [comment] 2019-09-05 18:44
> I plan to, but keep in mind, you definitely need proper scale for AR.

Yes, sure)

**Closed** 2019-09-10 15:36 UTC
Labels: arc: compatibility, arc: rendering & effects, type: bug

**Comment by Deankovitch** [comment] 2020-10-21 14:43
I'm getting this "black faces error" also on pure Three JS project.
In my project, the model is partially black. I'm using FBX exported from Maya. 
After checking everything from faces normals, to texture colors and UV smooth values, I decided to make a test recreating the material directly in Three JS. To my surprise, everything starts to render properly.
So, for those are facing this black faces issue in ThreeJS project, here's a workaround

`FBXloader.load( 'model.fbx', function ( object ) {
	 	object.traverse( function ( child ) {
			if ( child.isMesh ) {
            	var newMat = new THREE.MeshStandardMaterial({
            		map: child.material.map,
            		metalnessMap: child.material.metalnessMap,
            		roughnessMap: child.material.roughnessMap,
            		normalMap: child.material.normalMap,
            		aoMap: child.material.aoMap,
            	});
            	child.material = newMat;
            }
        });
	});`


Unfortunately for the model viewer there isn't a workaround since it is some kind of a black box around the base Three JS

**Comment by elalish** [comment] 2020-10-21 16:11
@Deankovitch What did you use to convert the FBX to glTF? That's what you'll want for model-viewer, and if it's generating black faces, please file a bug on that glTF exporter. Also make sure to check it with the Khronos glTF validator.
