### ISSUE TITLE
Quality test web page results are stretched

### ISSUE THREAD

**Issue by johnpallett** [GoogleWebComponents/model-viewer#517] opened 2019-05-01 18:57 UTC
### Description

The images at [https://googlewebcomponents.github.io/model-viewer/test/fidelity/results-viewer.html](https://googlewebcomponents.github.io/model-viewer/test/fidelity/results-viewer.html) are stretched

#### Live Demo
https://googlewebcomponents.github.io/model-viewer/test/fidelity/results-viewer.html

### Browser Affected
- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

**Comment by cdata** [comment] 2019-05-01 19:47
Dupe of #508 and already fixed in #516

**Closed by cdata** 2019-05-01 19:47 UTC
