### ISSUE TITLE
Textures in model-viewer - completely black

### ISSUE THREAD

**Issue by mischoko** [GoogleWebComponents/model-viewer#736] opened 2019-08-31 15:00 UTC
I've been noticing an issue with model-viewer displaying .gltf models with pure black texture instead of their default diffuse. I haven't tested the .usdz yet. 
Is this on my end or is that a global issue? 

Thanks

![astro_bug](https://user-images.githubusercontent.com/45178470/64065692-cd743980-cc10-11e9-9108-8fe822ec698b.png)

**Comment by cdata** [comment] 2019-09-03 15:13
Thanks for reporting @mischoko . It looks like this may be a bug, as we have received another report in https://github.com/GoogleWebComponents/model-viewer/issues/679#issuecomment-527468131 suggesting that some models have regressed.

If you could help us out, our original demo at https://model-viewer.glitch.me/ does _not_ exhibit the problem. Could you share the model and `<model-viewer>` configuration that reproduces this problem?

Also, if you can share the browser and hardware you took that screenshot on, that would be very helpful as well 🙏

**Comment by mischoko** [comment] 2019-09-03 16:12
Hmm, to give you a 100% answer I will have to check all my devices both iOS and Android. As far as I'm able to check the issue at the moment, I can tell that one of my desktops with Chrome v.  76.0.3809.132 is having this black-material bug even with the astronaut demo. However, my Android Phone with the exact same version of Chrome seems to be doing just fine. 
Tomorrow I'll quadruple-check with my other desktops and mobile devices to get a bit of broader analysis.

**Comment by cdata** [comment] 2019-09-03 16:49
Thanks for that detail @mischoko . Given what you have described, it sounds like the bug _could_ be hardware dependent. If you can share any details of the GPU in your desktop, that would be very helpful.

Also, could you share what model your Android phone is?

**Comment by mischoko** [comment] 2019-09-03 16:55
I've done a quick check on my other PC via Teamviewer and as you have mentioned, it seems to be a problem of this particular hardware setting. The Android is Honor 7A.

As for my setup at the moment - it's just a random conglomerate of pieces I threw together before I finish my main build. It does not even have a proper graphics card. I run it on in-built Intel HD 4600. Also, Win 7 if that's relevant in any way.

**Comment by cdata** [comment] 2019-09-03 16:56
That's very helpful info, thanks @mischoko !

**Comment by mischoko** [comment] 2019-09-03 16:57
@cdata No problem, I'll get you an update tomorrow when I get it tested on other devices as well.

**Comment by mischoko** [comment] 2019-09-04 09:10
Alright, I've done some testing with 3 Samsungs (no idea about the chrome version or the phones themselves) 1 iPhone X, and 1 Honor 6A - everything worked fine. Also iPad pro 2017 and 2018 both OK on Safari and Chrome. Other two desktops of unknown hardware configurations - OK.

So I think it's safe to say that it might very well be an issue with my hardware in the PC I mentioned in the previous comment.

**Comment by AytoMaximo** [comment] 2019-09-04 12:53
> If you could help us out, our original demo at https://model-viewer.glitch.me/ does _not_ exhibit the problem. Could you share the model and `<model-viewer>` configuration that reproduces this problem?

I'll try to share some information too. As I've already mentioned in #679 my device (Xiaomi Redmi 4A) was previously rendering black objects, but in the case of model-viewer.glitch.me there is no object visible at all. 

In our own [case](https://image.faradise.ru/arcore.html) we're using the following config:
`<model-viewer ar src="https://237529.selcdn.ru//awespace/product/6190/8786.glb" alt="3d model Faradise" auto-rotate camera-controls background-color="#ffffff" ios-src="https://237529.selcdn.ru/faradise/product/6190/8786.usdz" ></model-viewer>`

And it's black everywhere (PC, iOS..) and also not visible at all on Xiaomi device.

**Comment by elalish** [comment] 2019-09-09 18:12
I'm closing this as no repro, and since #679 has also been resolved as unrelated. Feel free to reopen if you find any standard hardware that reproduces it.

**Closed by elalish** 2019-09-09 18:12 UTC
Labels: arc: compatibility, arc: rendering & effects, type: bug

**Comment by androidparth90** [comment] 2021-10-30 08:32
I am facing the same issue with one of my models (.glb). I have attached the same for reference over here. Can this one be re-opened please?

**Comment by SilvioDiMatteo** [comment] 2021-11-11 11:44
I'm facing this issue too, on iOS in the 3D view, some parts of the model are total black only, if I switch to AR it is totally correct.
The weird thing is that if I reload the scene, the model starts working properly in the 3D view too.

**Comment by samaneh-kazemi** [comment] 2021-11-11 18:14
@SilvioDiMatteo Hi, this is an iOS issue and we're waiting for them to fix it. 
As a workaround you can pin v1.8 until our next release comes, e.g.
```
 <script type="module" src="https://unpkg.com/@google/model-viewer@1.8.0/dist/model-viewer.min.js"></script>
 ```

**Comment by Tommyhuls** [comment] 2021-12-08 20:09
@samaneh-kazemi 
Any news on this issue? We are using meshoptdecoder and this seems to not work with v1.8...

**Comment by elalish** [comment] 2021-12-08 20:52
There are open issues for this; unfortunately nearly all rendering bugs results in black pixels, so you can't assume any  two issues are automatically related by looking at the render. The most recent is a Safari 15.1 bug, and there's a work around coming down in the next three.js release, which we'll pick up in our next release, probably in  January.

**Comment by Udara-Sampath** [comment] 2022-01-01 15:31
This also happened to me, I tried completely changing texture names and relinking them before exporting as .glb and it worked
