### ISSUE TITLE
Problems displaying model in AR

### ISSUE THREAD

**Issue by arturomarruffo** [GoogleWebComponents/model-viewer#692] opened 2019-08-05 20:30 UTC
The GLB file is being displayed correctly on the website, but it suddenly stopped working in AR mode.

https://www.nextlatam.com/modelviewer/sodimac_demo.html

- [x] Chrome
- [x] Android
- model-viewer: v0.5.0

**Comment by cdata** [comment] 2019-08-05 22:22
Hey, thanks for reporting! It does indeed seem like there is an issue. I'm looking into it.

**Comment by cdata** [comment] 2019-08-06 15:39
Closing this one as a dupe of #693

**Closed by cdata** 2019-08-06 15:39 UTC
Labels: arc: ar, arc: compatibility, type: bug
