### ISSUE TITLE
HDR Environment not lighting models on Samsung Galaxy S8 or S9

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#637] opened 2019-06-13 19:14 UTC
### Description

Currently testing viewing a PBR model on a Samsung Galaxy S8 and S9 and am running into an issue where it appears unlit.
<img width="477" alt="Screen Shot 2019-06-13 at 2 24 54 PM" src="https://user-images.githubusercontent.com/190692/59457975-7ddb5a00-8de7-11e9-922d-838018120a22.png">

I have stage lighting set to 0, and if I turn stage lighting back on, then you do see it lit:

<img width="450" alt="Screen Shot 2019-06-13 at 2 25 56 PM" src="https://user-images.githubusercontent.com/190692/59458363-47eaa580-8de8-11e9-833d-2e794959d56f.png">

Caveat: I am testing this in Browserstack since I don't have an actual S8 or S9, however browserstack is just a video feed from real devices. It works on an S10.

I get the following in console:

<img width="1194" alt="Screen Shot 2019-06-13 at 2 26 08 PM" src="https://user-images.githubusercontent.com/190692/59460545-58e9e580-8ded-11e9-8cb7-aba54eab6e93.png">

#### Live Demo
https://obtainable-pancake-1.glitch.me/

### OS & Browser Affected
<img width="368" alt="Screen Shot 2019-06-13 at 3 12 28 PM" src="https://user-images.githubusercontent.com/190692/59460690-ae25f700-8ded-11e9-982e-39db3c9a0038.png">

### Versions

- model-viewer: v0.3.1
- three.js: r101

**Comment by cdata** [comment] 2019-06-13 21:28
Thanks for filing this @pushmatrix . What is that tool that you are using to test those devices?

Is this a dupe of #574 ?

cc @elalish

**Comment by elalish** [comment] 2019-06-13 22:01
I was guessing it was a dupe of #601. Does turning on PMREM fix it?

**Comment by elalish** [comment] 2019-06-13 22:09
Nevermind, I bet @cdata is right. Our environment map generation uses half float textures, and when that's not supported, everything down stream of that will fail. OES_texture_float_linear and EXT_shader_texture_lod are pretty critical to us now. We might want to decide if we should build an IBL system that doesn't rely on these extensions.

**Comment by pushmatrix** [comment] 2019-06-14 16:11
@cdata I use [Browserstack](browserstack.com):

Amazing tool. It spins up actual devices and lets you remotely control them from the web. You even have access to DevTools on them.

![browserstack](https://user-images.githubusercontent.com/190692/59522637-2dbecf00-8e9d-11e9-81d1-c44b5fb1bfe3.gif)

**Comment by cdata** [comment] 2019-06-14 16:29
That is amazing 😍 gonna purge Sauce Labs with fire now...

**Comment by elalish** [comment] 2019-07-23 15:59
Closed via #591

**Closed by elalish** 2019-07-23 15:59 UTC
Labels: arc: rendering & effects, flag: duplicate, type: bug

**Comment by elalish** [comment] 2019-07-23 16:06
@pushmatrix I'm pretty confident this is fixed, but I don't have the right device to test the repro. Can you check and let me know if this problem persists?

**Comment by pushmatrix** [comment] 2019-07-24 15:44
@elalish Just tested on an S8 and confirm it works correctly. Thanks for the fix!
