### ISSUE TITLE
Camera randomly jerks around when tumbling the model

### ISSUE THREAD

**Issue by pushmatrix** [GoogleWebComponents/model-viewer#800] opened 2019-10-07 19:27 UTC
### Description

I've noticed that after https://github.com/GoogleWebComponents/model-viewer/pull/755, the camera jerks around randomly when I try rotating a model in a single direction.

![tumble](https://user-images.githubusercontent.com/190692/66342046-8582b980-e916-11e9-990a-8554b55931c9.gif)

I'm just swiping to the right on this continuously, and notice how it jumps back every once in a while.

![jerk](https://user-images.githubusercontent.com/190692/66342049-874c7d00-e916-11e9-88ff-75085494c110.gif)

#### Live Demo
Visit https://googlewebcomponents.github.io/model-viewer/ 

Keep spinning the model in one direction.

This happens in Desktop Safari and iOS Safari every time. It only seems to happen in Chrome if the web inspector is open. Maybe it suggests it has something to do with viewer width.

If you make your window like this, it should happen:
<img width="888" alt="Screen Shot 2019-10-07 at 3 23 01 PM" src="https://user-images.githubusercontent.com/190692/66342180-d5618080-e916-11e9-8fad-c798e10d36c5.png">

### OS

- [ ] Android
- [x] iOS
- [ ] Linux
- [x] MacOS
- [ ] Windows

### Versions

- model-viewer: v0.6.2
- three.js: r108

**Comment by elalish** [comment] 2019-10-07 23:06
I can't repro on Safari and this looks like a dupe of #778, which I already fixed. Can you verify this is still happening on master?

**Comment by pushmatrix** [comment] 2019-10-08 01:56
I can confirm this is still happening on master.

**Comment by elalish** [comment] 2019-10-08 15:57
Okay, I wasn't able to repro on Safari, but on Chrome I can. As you say, only with dev tools open, but the size of the window doesn't seem to matter. I'll look into it. Thanks for bearing with me!

**Closed** 2019-10-09 21:00 UTC
Labels: arc: interaction, type: bug
